SmiteshP/nvim-gps

- lua/nvim-gps/init.lua
I added some basic support for elixir
I see you have the filename in your demo gifs—is that part of your configuration?
> Add elixir support

- lua/nvim-gps/init.lua
Icons from the user's configuration are not applied. It's a one-liner fix.
> Fix custom icons not being applied

- README.md
if you can export a table then windline can render a status with different highlights icon vs text
> add windline

- queries/javascript/nvimGPS.scm
- queries/typescript/nvimGPS.scm
* Arrow function methods in JS and TS
* Jest tests in JS and TS
* Arrow functions in TypeScript
Let me know your thoughts!
> Add some more JS and TS queries

- README.md
- lua/nvim-gps/init.lua
- lua/nvim-gps/utils.lua
- queries/lua/nvimGPS.scm
> Add container type capture and queries for lua tables

- README.md
- lua/nvim-gps/init.lua
- queries/ruby/nvimGPS.scm
https://user-images.githubusercontent.com/120483/134683022-171d7271-0465-4853-b1ab-a30c79c1a161.mov
> Add Ruby support

- lua/nvim-gps/init.lua
> html: fix for multiline tags

- README.md
- lua/nvim-gps/init.lua
> feat: Add depth limit feature

- README.md
- lua/nvim-gps/init.lua
- queries/json/nvimGPS.scm
Not sure if this is the best approach, as I have no experience with the treesitter query language. Thought this might be a good start (with the possibility of adding support for javascript objects and lua tables as well)
> feat: add support for json

- README.md
- lua/nvim-gps/init.lua
- queries/yaml/nvimGPS.scm
Back again with yaml support 😃
> feat: add support for yaml

- README.md
- lua/nvim-gps/init.lua
> feat: Option to disable icons

- README.md
- queries/php/nvimGPS.scm
This commit introduce simple php support.
I will try to improve it step by step.
> Add php support

- queries/lua/nvimGPS.scm
> lua: breaking changes in parser - update queries

- README.md
- lua/nvim-gps/init.lua
get_data returns context in table format
get_location uses this data to return a nice string
fix #68
> feat: seperate out get_data and get_location functions

- README.md
- lua/nvim-gps/init.lua
> feat: Add optional arguments to get_location function

- README.md
- queries/c_sharp/nvimGPS.scm
Add support for C#
- method
- lambda expression
> feat: add support for C#

- README.md
- lua/nvim-gps/init.lua
- queries/latex/nvimGPS.scm
It will capture the sections (chapters/sections/subsections/...)
For general environments (lemmas/equations/...), it will only capture those which has a label.
> feat: add basic support for latex

- lua/nvim-gps/init.lua
- queries/scss/nvimGPS.scm
- queries/tsx/nvimGPS.scm
https://user-images.githubusercontent.com/33498670/160940544-fec85a60-a21b-4a78-adfb-9d22ff49b9e5.mov
PS: really useful plugin btw, thank you a lot @SmiteshP
> add queries for scss

- lua/nvim-gps/init.lua
> update nvim 0.7 treesitter api

- README.md
- lua/nvim-gps/init.lua
- queries/haskell/nvimGPS.scm
Added Haskell Support:
- Functions
- Functions in Where Clauses
- Functions in Let...In
- Operators
- Datatypes
- Records
- Typeclasses
- Instances
> Haskell support
